### ISSUE TITLE
PASS with or without quotation marks on the integer value of the response body

### ISSUE THREAD

**Issue by sg5314** [zoncoen/scenarigo#444]
Hello. Thank you for providing us with a great tool!
I recently started using this tool and would like to know one thing.

## Description
I was checking the API response for expected results as follows.
However, in the response body, I found that number of `integer` will pass with or without a quotation mark.
( I understand that if want to check an integer in a string format, I would do something like `"' 123 '"`.)
Is it OK to PASS with or without this quotation mark?

```yaml
- title: Check int response body
  protocol: http
  request:
    method: GET
    url: 'http://localhost:8080/users'
  expect:
    code: OK
    header:
      Content-Type: application/json
    body:
      tags:
        - id: '1' # 1 or '1' is fine
          name: 'user-name-1'
```

I would appreciate it if you could let me know.
