### ISSUE TITLE
[Feature Request] Introduce `definedWithDefault(vars.foo.bar, "default value")` built-in function in scenarigo template

### ISSUE THREAD

**Issue by youxkei** [zoncoen/scenarigo#489]
I often use the following idiom in YAML files that are included by other scenarios:

```yaml
vars:
  params:
    foo: '{{ defined(vars.params.foo) ? vars.params.foo : "default foo" }}'
    bar: '{{ defined(vars.params.bar) ? vars.params.bar : "default bar" }}'
```
With this idiom, I need to repeat the same variable name, and it can be a bit hard to read if the variable name is long.

So, how about introducing a built-in function like `definedWithDefault` as a kind of syntactic sugar?

```yaml
vars:
  params:
    foo: '{{ definedWithDefault(vars.params.foo, "default foo") }}' 
    bar: '{{ definedWithDefault(vars.params.bar, "default bar") }}'
```

`'{{ definedWithDefault(vars.params.foo, "default foo") }}'` have the same semantics as `'{{ defined(vars.params.foo) ? vars.params.foo : "default foo" }}'`.

I'm temporarily calling it `definedWithDefault`, but I'd appreciate any better naming suggestions. Perhaps `getWithDefault`...?
