### ISSUE TITLE
[Feature Request] Introduce `assert.any` in scenarigo template that always succeeds with ignoring the actual value

### ISSUE THREAD

**Issue by youxkei** [zoncoen/scenarigo#492]
In scenarios that is included by other scenarios, we often want to use `assert.any` as a default expected value that always succeeds:

```yaml
vars:
  expect:
    foo: '{{ defined(vars.expect.foo) ? vars.expect.foo : assert.any }}'
```

Currently, since assert.any does not exist, we are using a plugin:

```yaml
vars:
  expect:
    foo: '{{ defined(vars.expect.foo) ? vars.expect.foo : plugins.main.AssertAny }}'
```
```go
var AssertAny = assert.AssertionFunc(func(any) error {
	return nil
})
```
While it is achievable with a plugin, we would be happy if assert.any could be introduced as a built-in function, because we use this feature quite often.
